import { MovementPattern, Equipment, TrainingLevel } from '@prisma/client';

export interface ExerciseSeedData {
  name: string;
  pattern: MovementPattern;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  equipment: Equipment[];
  level: TrainingLevel;
  gifUrl?: string;
  clinicalNotes?: string[];
}

const I = TrainingLevel.INICIANTE;
const M = TrainingLevel.INTERMEDIO;
const A = TrainingLevel.AVANCADO;

export const exerciseSeedData: ExerciseSeedData[] = [

  // ─── PEITO — EMPURRAR HORIZONTAL ─────────────────────────────────────────

  // Peitoral maior (parte média)
  { name: 'Flexões Clássicas', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Flexões com Halteres (Pegada Neutra)', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Supino com Halteres', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Fly com Halteres (Deitado)', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },

  // Peitoral superior
  { name: 'Flexões Inclinadas (Pés Elevados)', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['triceps', 'deltoides'],
    equipment: [Equipment.PESO_CORPORAL, Equipment.BANCO], level: M },
  { name: 'Supino Inclinado com Halteres', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Fly Inclinado com Halteres', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },

  // Peitoral inferior
  { name: 'Flexões Declinadas (Mãos Elevadas)', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral_inferior'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.PESO_CORPORAL, Equipment.BANCO], level: I },
  { name: 'Dips (Paralelas — Inclinado para Frente)', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral_inferior'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.PARALELAS], level: M, clinicalNotes: ['evitar_ombro'] },

  // Compostos com barra / máquinas
  { name: 'Supino com Barra', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.BARRA, Equipment.BANCO], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Peck Deck (Butterfly)', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.MAQUINAS], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Cable Fly', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.CABO], level: I },

  // ─── COSTAS — PUXAR VERTICAL ─────────────────────────────────────────────

  { name: 'Pull-ups (Barra Fixa)', pattern: MovementPattern.PUXAR_VERTICAL,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['romboides', 'core'],
    equipment: [Equipment.BARRA_FIXA], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Chin-ups', pattern: MovementPattern.PUXAR_VERTICAL,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['romboides'],
    equipment: [Equipment.BARRA_FIXA], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Pull-over com Halter', pattern: MovementPattern.PUXAR_VERTICAL,
    primaryMuscles: ['dorsal', 'peitoral'], secondaryMuscles: ['triceps_longo'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Lat Pulldown (Polia)', pattern: MovementPattern.PUXAR_VERTICAL,
    primaryMuscles: ['dorsal'], secondaryMuscles: ['biceps', 'romboides'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Pull-up Assistido com Elástico', pattern: MovementPattern.PUXAR_VERTICAL,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['romboides'],
    equipment: [Equipment.BARRA_FIXA, Equipment.RESISTANCE_BAND], level: I },
  { name: 'Dead Hang (Pendurado na Barra)', pattern: MovementPattern.PUXAR_VERTICAL,
    primaryMuscles: ['dorsal', 'antebraco'], secondaryMuscles: ['core'],
    equipment: [Equipment.BARRA_FIXA], level: I },

  // ─── COSTAS — PUXAR HORIZONTAL ───────────────────────────────────────────

  { name: 'Remada com Halteres (Bilateral)', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps', 'trapezio'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Remada Unilateral com Halter', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I },
  { name: 'Remada Curvada com Halteres', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['dorsal', 'trapezio'], secondaryMuscles: ['biceps', 'eretores_espinhais'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Australian Pull-ups (Remada Invertida)', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps', 'core'],
    equipment: [Equipment.BARRA_FIXA, Equipment.PESO_CORPORAL], level: I },
  { name: 'Hiperextensões no Chão (Superman Invertido)', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['eretores_espinhais', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: '"Superman" (Calistenia)', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['eretores_espinhais', 'gluteos'], secondaryMuscles: ['deltoides_posterior'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Deadlift com Halteres', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['eretores_espinhais', 'isquiotibiais', 'gluteos'], secondaryMuscles: ['trapezio', 'core'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Seated Cable Row', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Band Pull-Apart', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['romboides', 'deltoides_posterior'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.RESISTANCE_BAND], level: I },

  // ─── OMBROS — EMPURRAR VERTICAL ──────────────────────────────────────────

  { name: 'Shoulder Press com Halteres', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'trapezio'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Elevação Frontal com Halteres', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides_anterior'], secondaryMuscles: ['peitoral_superior'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Elevação Lateral com Halteres', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides_lateral'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Pike Push-ups', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'trapezio'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Reverse Fly com Halteres', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides_posterior', 'romboides'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Face Pull com Elástico', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides_posterior', 'manguito_rotador'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.RESISTANCE_BAND], level: I },
  { name: 'Remada Alta com Halteres', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides', 'trapezio'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Arnold Press', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Overhead Press com Barra (OHP)', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'core'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_ombro'] },

  // ─── BRAÇOS — PUXAR HORIZONTAL (bíceps) ──────────────────────────────────

  { name: 'Curl com Halteres (Alternado)', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['biceps'], secondaryMuscles: ['braquial', 'braquioradial'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Curl Martelo (Hammer Curl)', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['braquioradial', 'biceps'], secondaryMuscles: ['braquial'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Curl com Barra', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['biceps'], secondaryMuscles: ['braquial'],
    equipment: [Equipment.BARRA], level: I },
  { name: 'Curl no Cabo', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: [Equipment.CABO], level: I },

  // ─── BRAÇOS — EMPURRAR HORIZONTAL (tríceps) ──────────────────────────────

  { name: 'Dips para Tríceps', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['triceps'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.BANCO, Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Flexões Diamante', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['triceps'], secondaryMuscles: ['peitoral', 'deltoides'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Extensão de Tríceps com Halter (Acima da Cabeça)', pattern: MovementPattern.EMPURRAR_VERTICAL,
    primaryMuscles: ['triceps_longo'], secondaryMuscles: [],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Kickback com Halteres', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Tricep Pushdown no Cabo', pattern: MovementPattern.EMPURRAR_HORIZONTAL,
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: [Equipment.CABO], level: I },

  // ─── ANTEBRAÇO ────────────────────────────────────────────────────────────

  { name: "Farmer's Walk com Halteres", pattern: MovementPattern.CORE,
    primaryMuscles: ['antebraco', 'trapezio'], secondaryMuscles: ['core', 'gluteos'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Wrist Curls com Halteres', pattern: MovementPattern.PUXAR_HORIZONTAL,
    primaryMuscles: ['antebraco'], secondaryMuscles: [],
    equipment: [Equipment.HALTERES], level: I },

  // ─── PERNAS — DOMINANTE JOELHO ───────────────────────────────────────────

  { name: 'Agachamento Livre (Calistenia)', pattern: MovementPattern.DOMINANTE_JOELHO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Goblet Squat com Halter', pattern: MovementPattern.DOMINANTE_JOELHO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['core', 'adutores'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Lunges (Avanço) com Halteres', pattern: MovementPattern.DOMINANTE_JOELHO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Bulgarian Split Squat', pattern: MovementPattern.DOMINANTE_JOELHO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: M, clinicalNotes: ['evitar_joelho'] },
  { name: 'Agachamento com Barra (Back Squat)', pattern: MovementPattern.DOMINANTE_JOELHO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.BARRA, Equipment.RACK], level: M, clinicalNotes: ['evitar_joelho', 'evitar_lombar'] },
  { name: 'Leg Press', pattern: MovementPattern.DOMINANTE_JOELHO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.MAQUINAS], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Step-up com Halteres', pattern: MovementPattern.DOMINANTE_JOELHO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I },
  { name: 'Pistol Squat', pattern: MovementPattern.DOMINANTE_JOELHO,
    primaryMuscles: ['quadriceps'], secondaryMuscles: ['gluteos', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_joelho'] },

  // ─── PERNAS — DOMINANTE ANCA (isquiotibiais / glúteos) ───────────────────

  { name: 'Romanian Deadlift com Halteres', pattern: MovementPattern.DOMINANTE_ANCA,
    primaryMuscles: ['isquiotibiais', 'gluteos'], secondaryMuscles: ['eretores_espinhais'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Glute Bridge', pattern: MovementPattern.DOMINANTE_ANCA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Nordic Curl', pattern: MovementPattern.DOMINANTE_ANCA,
    primaryMuscles: ['isquiotibiais'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: A },
  { name: 'Hip Thrust com Halter', pattern: MovementPattern.DOMINANTE_ANCA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I },
  { name: 'Hip Thrust com Barra', pattern: MovementPattern.DOMINANTE_ANCA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.BARRA, Equipment.BANCO], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Kettlebell Swing', pattern: MovementPattern.DOMINANTE_ANCA,
    primaryMuscles: ['gluteos', 'isquiotibiais'], secondaryMuscles: ['core', 'deltoides'],
    equipment: [Equipment.KETTLEBELL], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Clamshell com Elástico', pattern: MovementPattern.DOMINANTE_ANCA,
    primaryMuscles: ['gluteos_medios', 'abdutores'], secondaryMuscles: [],
    equipment: [Equipment.RESISTANCE_BAND], level: I },
  { name: 'Donkey Kick', pattern: MovementPattern.DOMINANTE_ANCA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.PESO_CORPORAL], level: I },

  // Gémeos
  { name: 'Elevação de Gémeos (Calf Raises)', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['gastrocnemios'], secondaryMuscles: ['soleo'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Elevação Unilateral de Gémeos', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['gastrocnemios', 'soleo'], secondaryMuscles: [],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Calf Raises com Halteres', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['gastrocnemios'], secondaryMuscles: ['soleo'],
    equipment: [Equipment.HALTERES], level: I },

  // ─── CORE ─────────────────────────────────────────────────────────────────

  { name: 'Crunch', pattern: MovementPattern.CORE,
    primaryMuscles: ['reto_abdominal'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Sit-up', pattern: MovementPattern.CORE,
    primaryMuscles: ['reto_abdominal', 'iliopsoas'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Leg Raises (Elevação de Pernas)', pattern: MovementPattern.CORE,
    primaryMuscles: ['iliopsoas', 'reto_abdominal'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.PESO_CORPORAL], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Toes to Bar', pattern: MovementPattern.CORE,
    primaryMuscles: ['reto_abdominal', 'iliopsoas'], secondaryMuscles: ['obliquos', 'dorsal'],
    equipment: [Equipment.BARRA_FIXA], level: A },
  { name: 'Russian Twist com Halter', pattern: MovementPattern.CORE,
    primaryMuscles: ['obliquos'], secondaryMuscles: ['reto_abdominal'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Side Plank', pattern: MovementPattern.CORE,
    primaryMuscles: ['obliquos', 'quadrado_lombar'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Bicycle Crunch', pattern: MovementPattern.CORE,
    primaryMuscles: ['obliquos', 'reto_abdominal'], secondaryMuscles: [],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Prancha (Plank)', pattern: MovementPattern.CORE,
    primaryMuscles: ['core', 'transverso_abdominal'], secondaryMuscles: ['deltoides', 'gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Hollow Body Hold', pattern: MovementPattern.CORE,
    primaryMuscles: ['transverso_abdominal', 'reto_abdominal'], secondaryMuscles: ['iliopsoas'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Dead Bug', pattern: MovementPattern.CORE,
    primaryMuscles: ['transverso_abdominal', 'core'], secondaryMuscles: ['eretores_espinhais'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Bird Dog', pattern: MovementPattern.CORE,
    primaryMuscles: ['eretores_espinhais', 'gluteos'], secondaryMuscles: ['core'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Ab Wheel Rollout', pattern: MovementPattern.CORE,
    primaryMuscles: ['core', 'transverso_abdominal'], secondaryMuscles: ['dorsal'],
    equipment: [Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_lombar'] },

  // ─── FULL BODY / LOCOMOÇÃO ────────────────────────────────────────────────

  { name: 'Burpees', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['quadriceps', 'peitoral', 'deltoides'], secondaryMuscles: ['core', 'gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Thrusters com Halteres', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['quadriceps', 'deltoides', 'gluteos'], secondaryMuscles: ['core', 'triceps'],
    equipment: [Equipment.HALTERES], level: M },
  { name: 'Clean & Press com Halteres', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['gluteos', 'deltoides', 'trapezio'], secondaryMuscles: ['core', 'biceps'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Mountain Climbers', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['core', 'iliopsoas'], secondaryMuscles: ['deltoides', 'quadriceps'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Corrida / Passadeira', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['quadriceps', 'isquiotibiais', 'gluteos', 'gastrocnemios'], secondaryMuscles: ['core'],
    equipment: [Equipment.CARDIO_EQ], level: I, clinicalNotes: ['evitar_joelho', 'evitar_tornozelo'] },
  { name: 'Caminhada Inclinada', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['gluteos', 'isquiotibiais', 'gastrocnemios'], secondaryMuscles: ['core'],
    equipment: [Equipment.CARDIO_EQ], level: I },
  { name: 'Bicicleta Estática', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['gastrocnemios'],
    equipment: [Equipment.CARDIO_EQ], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Remo (Máquina)', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['dorsal', 'isquiotibiais', 'gluteos'], secondaryMuscles: ['biceps', 'core'],
    equipment: [Equipment.CARDIO_EQ], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Salto à Corda', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['gastrocnemios', 'quadriceps'], secondaryMuscles: ['core'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_tornozelo'] },
  { name: 'Box Jump', pattern: MovementPattern.LOCOMOCAO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['gastrocnemios', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: M, clinicalNotes: ['evitar_joelho'] },
];
