import { MovementPattern, Equipment, TrainingLevel } from '@prisma/client';

export interface ExerciseSeedData {
  name: string;
  pattern: MovementPattern;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  equipment: Equipment[];
  level: TrainingLevel;
  gifUrl?: string;
  clinicalNotes?: string[];
}

const I = TrainingLevel.INICIANTE;
const M = TrainingLevel.INTERMEDIO;
const A = TrainingLevel.AVANCADO;
const EH = MovementPattern.EMPURRAR_HORIZONTAL;
const EV = MovementPattern.EMPURRAR_VERTICAL;
const PH = MovementPattern.PUXAR_HORIZONTAL;
const PV = MovementPattern.PUXAR_VERTICAL;
const DJ = MovementPattern.DOMINANTE_JOELHO;
const DA = MovementPattern.DOMINANTE_ANCA;
const CO = MovementPattern.CORE;
const LO = MovementPattern.LOCOMOCAO;

export const exerciseSeedData: ExerciseSeedData[] = [

  // ══════════════════════════════════════════════════════════════
  // EMPURRAR HORIZONTAL — Peito / Tríceps
  // ══════════════════════════════════════════════════════════════

  // Peso corporal
  { name: 'Flexões Clássicas', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Flexões Inclinadas (Pés Elevados)', pattern: EH,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['triceps', 'deltoides'],
    equipment: [Equipment.PESO_CORPORAL, Equipment.BANCO], level: M },
  { name: 'Flexões Declinadas (Mãos Elevadas)', pattern: EH,
    primaryMuscles: ['peitoral_inferior'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.PESO_CORPORAL, Equipment.BANCO], level: I },
  { name: 'Flexões Diamante', pattern: EH,
    primaryMuscles: ['triceps'], secondaryMuscles: ['peitoral', 'deltoides'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Flexões Explosivas (Clap Push-up)', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.PESO_CORPORAL], level: A },
  { name: 'Flexões Archer', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.PESO_CORPORAL], level: A },
  { name: 'Flexões Unilaterais Assistidas', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_ombro'] },
  { name: 'Pike Push-ups', pattern: EH,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'trapezio'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Dips para Tríceps (Banco)', pattern: EH,
    primaryMuscles: ['triceps'], secondaryMuscles: ['deltoides_anterior', 'peitoral_inferior'],
    equipment: [Equipment.BANCO, Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Dips (Paralelas — Peito)', pattern: EH,
    primaryMuscles: ['peitoral_inferior'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.PARALELAS], level: M, clinicalNotes: ['evitar_ombro'] },

  // Halteres
  { name: 'Supino com Halteres', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Supino Inclinado com Halteres', pattern: EH,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Supino Declinado com Halteres', pattern: EH,
    primaryMuscles: ['peitoral_inferior'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Fly com Halteres (Deitado)', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Fly Inclinado com Halteres', pattern: EH,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Extensão de Tríceps com Halter (Acima da Cabeça)', pattern: EV,
    primaryMuscles: ['triceps_longo'], secondaryMuscles: [],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Kickback com Halteres', pattern: EH,
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Flexões com Halteres (Pegada Neutra)', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.HALTERES], level: I },

  // Barra
  { name: 'Supino com Barra', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.BARRA, Equipment.BANCO], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Supino Inclinado com Barra', pattern: EH,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.BARRA, Equipment.RACK], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Supino Declinado com Barra', pattern: EH,
    primaryMuscles: ['peitoral_inferior'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.BARRA, Equipment.BANCO], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Close Grip Bench Press', pattern: EH,
    primaryMuscles: ['triceps'], secondaryMuscles: ['peitoral', 'deltoides_anterior'],
    equipment: [Equipment.BARRA, Equipment.BANCO], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Skull Crushers com Barra EZ', pattern: EH,
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: [Equipment.BARRA, Equipment.BANCO], level: M, clinicalNotes: ['evitar_ombro'] },

  // Cabo
  { name: 'Cable Fly (Cruzamento no Cabo)', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Low Cable Fly', pattern: EH,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.CABO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'High Cable Fly', pattern: EH,
    primaryMuscles: ['peitoral_inferior'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.CABO], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Tricep Pushdown no Cabo (Corda)', pattern: EH,
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: [Equipment.CABO], level: I },
  { name: 'Tricep Pushdown no Cabo (Barra)', pattern: EH,
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: [Equipment.CABO], level: I },
  { name: 'Overhead Tricep Extension no Cabo', pattern: EH,
    primaryMuscles: ['triceps_longo'], secondaryMuscles: [],
    equipment: [Equipment.CABO], level: I, clinicalNotes: ['evitar_ombro'] },

  // Máquinas
  { name: 'Peck Deck (Butterfly Machine)', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.MAQUINAS], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Machine Chest Press', pattern: EH,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['triceps', 'deltoides_anterior'],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'Machine Incline Press', pattern: EH,
    primaryMuscles: ['peitoral_superior'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'Tricep Machine (Extension)', pattern: EH,
    primaryMuscles: ['triceps'], secondaryMuscles: [],
    equipment: [Equipment.MAQUINAS], level: I },

  // ══════════════════════════════════════════════════════════════
  // PUXAR VERTICAL — Dorsal / Bíceps
  // ══════════════════════════════════════════════════════════════

  { name: 'Pull-ups (Pega Pronada)', pattern: PV,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['romboides', 'core'],
    equipment: [Equipment.BARRA_FIXA], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Chin-ups (Pega Supinada)', pattern: PV,
    primaryMuscles: ['biceps', 'dorsal'], secondaryMuscles: ['romboides'],
    equipment: [Equipment.BARRA_FIXA], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Pull-ups Pega Neutra', pattern: PV,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['romboides'],
    equipment: [Equipment.BARRA_FIXA], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Pull-up Assistido com Elástico', pattern: PV,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['romboides'],
    equipment: [Equipment.BARRA_FIXA, Equipment.RESISTANCE_BAND], level: I },
  { name: 'Negative Pull-ups', pattern: PV,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['core'],
    equipment: [Equipment.BARRA_FIXA], level: I },
  { name: 'Dead Hang', pattern: PV,
    primaryMuscles: ['dorsal', 'antebraco'], secondaryMuscles: ['core'],
    equipment: [Equipment.BARRA_FIXA], level: I },
  { name: 'Lat Pulldown (Polia) Pega Ampla', pattern: PV,
    primaryMuscles: ['dorsal'], secondaryMuscles: ['biceps', 'romboides'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Lat Pulldown Pega Neutra', pattern: PV,
    primaryMuscles: ['dorsal'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Lat Pulldown Pega Supinada', pattern: PV,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['romboides'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Straight Arm Pulldown no Cabo', pattern: PV,
    primaryMuscles: ['dorsal'], secondaryMuscles: ['triceps_longo'],
    equipment: [Equipment.CABO], level: M },
  { name: 'Pull-over com Halter', pattern: PV,
    primaryMuscles: ['dorsal', 'peitoral'], secondaryMuscles: ['triceps_longo'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Pull-over no Cabo', pattern: PV,
    primaryMuscles: ['dorsal'], secondaryMuscles: ['triceps_longo'],
    equipment: [Equipment.CABO], level: M },
  { name: 'Lat Pulldown com Elástico', pattern: PV,
    primaryMuscles: ['dorsal'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.RESISTANCE_BAND], level: I },
  { name: 'Machine Lat Pulldown', pattern: PV,
    primaryMuscles: ['dorsal'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.MAQUINAS], level: I },

  // ══════════════════════════════════════════════════════════════
  // PUXAR HORIZONTAL — Costas / Bíceps / Antebraços
  // ══════════════════════════════════════════════════════════════

  // Halteres
  { name: 'Remada Unilateral com Halter', pattern: PH,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I },
  { name: 'Remada com Halteres (Bilateral)', pattern: PH,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps', 'trapezio'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Remada Curvada com Halteres', pattern: PH,
    primaryMuscles: ['dorsal', 'trapezio'], secondaryMuscles: ['biceps', 'eretores_espinhais'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Deadlift com Halteres', pattern: PH,
    primaryMuscles: ['eretores_espinhais', 'isquiotibiais', 'gluteos'], secondaryMuscles: ['trapezio', 'core'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Curl com Halteres (Alternado)', pattern: PH,
    primaryMuscles: ['biceps'], secondaryMuscles: ['braquial', 'braquioradial'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Curl Martelo (Hammer Curl)', pattern: PH,
    primaryMuscles: ['braquioradial', 'biceps'], secondaryMuscles: ['braquial'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Curl Concentrado com Halter', pattern: PH,
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Curl Inclinado com Halteres', pattern: PH,
    primaryMuscles: ['biceps'], secondaryMuscles: ['braquial'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I },
  { name: 'Wrist Curls com Halteres', pattern: PH,
    primaryMuscles: ['antebraco'], secondaryMuscles: [],
    equipment: [Equipment.HALTERES], level: I },

  // Barra
  { name: 'Remada Curvada com Barra (Bent Over Row)', pattern: PH,
    primaryMuscles: ['dorsal', 'trapezio'], secondaryMuscles: ['biceps', 'eretores_espinhais'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Pendlay Row', pattern: PH,
    primaryMuscles: ['dorsal', 'trapezio'], secondaryMuscles: ['biceps', 'core'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Reverse Grip Barbell Row', pattern: PH,
    primaryMuscles: ['dorsal', 'biceps'], secondaryMuscles: ['romboides'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Deadlift Convencional com Barra', pattern: PH,
    primaryMuscles: ['eretores_espinhais', 'gluteos', 'isquiotibiais'], secondaryMuscles: ['trapezio', 'quadriceps', 'core'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Curl com Barra', pattern: PH,
    primaryMuscles: ['biceps'], secondaryMuscles: ['braquial'],
    equipment: [Equipment.BARRA], level: I },
  { name: 'Curl com Barra EZ', pattern: PH,
    primaryMuscles: ['biceps'], secondaryMuscles: ['braquioradial'],
    equipment: [Equipment.BARRA], level: I },

  // Cabo
  { name: 'Seated Cable Row (Pega Neutra)', pattern: PH,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Seated Cable Row (Pega Ampla)', pattern: PH,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps', 'trapezio'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Cable Row Unilateral', pattern: PH,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Face Pull no Cabo (Corda)', pattern: PH,
    primaryMuscles: ['deltoides_posterior', 'manguito_rotador'], secondaryMuscles: ['romboides', 'trapezio'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Curl no Cabo (Barra)', pattern: PH,
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: [Equipment.CABO], level: I },
  { name: 'Curl no Cabo (Corda)', pattern: PH,
    primaryMuscles: ['biceps', 'braquioradial'], secondaryMuscles: [],
    equipment: [Equipment.CABO], level: I },

  // Peso corporal
  { name: 'Australian Pull-ups (Remada Invertida)', pattern: PH,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps', 'core'],
    equipment: [Equipment.BARRA_FIXA, Equipment.PESO_CORPORAL], level: I },
  { name: '"Superman" (Hiperextensão no Chão)', pattern: PH,
    primaryMuscles: ['eretores_espinhais', 'gluteos'], secondaryMuscles: ['deltoides_posterior'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Band Pull-Apart', pattern: PH,
    primaryMuscles: ['romboides', 'deltoides_posterior'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.RESISTANCE_BAND], level: I },

  // Máquinas
  { name: 'Chest Supported Row na Máquina', pattern: PH,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'T-Bar Row', pattern: PH,
    primaryMuscles: ['dorsal', 'romboides'], secondaryMuscles: ['biceps', 'trapezio'],
    equipment: [Equipment.MAQUINAS], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Preacher Curl na Máquina', pattern: PH,
    primaryMuscles: ['biceps'], secondaryMuscles: [],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: "Farmer's Walk com Halteres", pattern: CO,
    primaryMuscles: ['antebraco', 'trapezio'], secondaryMuscles: ['core', 'gluteos'],
    equipment: [Equipment.HALTERES], level: I },

  // ══════════════════════════════════════════════════════════════
  // EMPURRAR VERTICAL — Ombros / Tríceps
  // ══════════════════════════════════════════════════════════════

  // Halteres
  { name: 'Shoulder Press com Halteres (Sentado)', pattern: EV,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'trapezio'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Shoulder Press com Halteres (Em Pé)', pattern: EV,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'trapezio', 'core'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Arnold Press', pattern: EV,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Elevação Lateral com Halteres', pattern: EV,
    primaryMuscles: ['deltoides_lateral'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Elevação Frontal com Halteres', pattern: EV,
    primaryMuscles: ['deltoides_anterior'], secondaryMuscles: ['peitoral_superior'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },
  { name: 'Reverse Fly com Halteres', pattern: EV,
    primaryMuscles: ['deltoides_posterior', 'romboides'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Remada Alta com Halteres', pattern: EV,
    primaryMuscles: ['deltoides', 'trapezio'], secondaryMuscles: ['biceps'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_ombro'] },

  // Barra
  { name: 'Overhead Press com Barra (OHP)', pattern: EV,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'core'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_ombro'] },
  { name: 'Push Press com Barra', pattern: EV,
    primaryMuscles: ['deltoides', 'triceps'], secondaryMuscles: ['gluteos', 'core'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_ombro'] },

  // Cabo
  { name: 'Elevação Lateral no Cabo', pattern: EV,
    primaryMuscles: ['deltoides_lateral'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Elevação Frontal no Cabo', pattern: EV,
    primaryMuscles: ['deltoides_anterior'], secondaryMuscles: [],
    equipment: [Equipment.CABO], level: I },
  { name: 'Rear Delt Fly no Cabo', pattern: EV,
    primaryMuscles: ['deltoides_posterior', 'romboides'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Face Pull no Cabo (com Elástico)', pattern: EV,
    primaryMuscles: ['deltoides_posterior', 'manguito_rotador'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.RESISTANCE_BAND], level: I },

  // Peso corporal
  { name: 'Pike Push-ups', pattern: EV,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'trapezio'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Handstand Push-up (Parede)', pattern: EV,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_ombro'] },

  // Máquinas
  { name: 'Machine Shoulder Press', pattern: EV,
    primaryMuscles: ['deltoides'], secondaryMuscles: ['triceps'],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'Rear Delt Machine (Reverse Peck Deck)', pattern: EV,
    primaryMuscles: ['deltoides_posterior', 'romboides'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'Machine Lateral Raise', pattern: EV,
    primaryMuscles: ['deltoides_lateral'], secondaryMuscles: ['trapezio'],
    equipment: [Equipment.MAQUINAS], level: I },

  // ══════════════════════════════════════════════════════════════
  // DOMINANTE JOELHO — Quadriceps / Glúteos
  // ══════════════════════════════════════════════════════════════

  // Peso corporal
  { name: 'Agachamento Livre (Calistenia)', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Wall Sit', pattern: DJ,
    primaryMuscles: ['quadriceps'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Lunges (Avanço) no Lugar', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Reverse Lunge (Avanço para Trás)', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Lateral Lunge (Avanço Lateral)', pattern: DJ,
    primaryMuscles: ['quadriceps', 'adutores'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Step-up (Sem Peso)', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.BANCO, Equipment.PESO_CORPORAL], level: I },
  { name: 'Pistol Squat (Assistido)', pattern: DJ,
    primaryMuscles: ['quadriceps'], secondaryMuscles: ['gluteos', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: M, clinicalNotes: ['evitar_joelho'] },
  { name: 'Pistol Squat', pattern: DJ,
    primaryMuscles: ['quadriceps'], secondaryMuscles: ['gluteos', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_joelho'] },
  { name: 'Saltos de Agachamento (Jump Squat)', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['gastrocnemios'],
    equipment: [Equipment.PESO_CORPORAL], level: M, clinicalNotes: ['evitar_joelho'] },
  { name: 'Sissy Squat', pattern: DJ,
    primaryMuscles: ['quadriceps'], secondaryMuscles: [],
    equipment: [Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_joelho'] },

  // Halteres
  { name: 'Goblet Squat com Halter', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['core', 'adutores'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Lunges (Avanço) com Halteres', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Sumo Squat com Halter', pattern: DJ,
    primaryMuscles: ['quadriceps', 'adutores'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Bulgarian Split Squat com Halteres', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: M, clinicalNotes: ['evitar_joelho'] },
  { name: 'Step-up com Halteres', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I },
  { name: 'Walking Lunges com Halteres', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_joelho'] },

  // Barra / Rack
  { name: 'Agachamento com Barra (Back Squat)', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.BARRA, Equipment.RACK], level: M, clinicalNotes: ['evitar_joelho', 'evitar_lombar'] },
  { name: 'Front Squat com Barra', pattern: DJ,
    primaryMuscles: ['quadriceps'], secondaryMuscles: ['gluteos', 'core'],
    equipment: [Equipment.BARRA, Equipment.RACK], level: M, clinicalNotes: ['evitar_joelho', 'evitar_lombar'] },
  { name: 'Box Squat com Barra', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.BARRA, Equipment.RACK], level: M, clinicalNotes: ['evitar_joelho'] },
  { name: 'Hack Squat com Barra', pattern: DJ,
    primaryMuscles: ['quadriceps'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_joelho'] },
  { name: 'Sumo Squat com Barra', pattern: DJ,
    primaryMuscles: ['quadriceps', 'adutores'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.BARRA, Equipment.RACK], level: M, clinicalNotes: ['evitar_joelho'] },
  { name: 'Zercher Squat', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['core', 'biceps'],
    equipment: [Equipment.BARRA], level: A, clinicalNotes: ['evitar_joelho', 'evitar_lombar'] },

  // Máquinas
  { name: 'Leg Press', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.MAQUINAS], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Leg Extension (Cadeira Extensora)', pattern: DJ,
    primaryMuscles: ['quadriceps'], secondaryMuscles: [],
    equipment: [Equipment.MAQUINAS], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Hack Squat (Máquina)', pattern: DJ,
    primaryMuscles: ['quadriceps'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.MAQUINAS], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Smith Machine Squat', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.SMITH], level: I, clinicalNotes: ['evitar_joelho'] },

  // Kettlebell
  { name: 'Goblet Squat com Kettlebell', pattern: DJ,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['core'],
    equipment: [Equipment.KETTLEBELL], level: I },

  // Gémeos (no padrão LOCOMOCAO)
  { name: 'Elevação de Gémeos Em Pé', pattern: LO,
    primaryMuscles: ['gastrocnemios'], secondaryMuscles: ['soleo'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Elevação Unilateral de Gémeos', pattern: LO,
    primaryMuscles: ['gastrocnemios', 'soleo'], secondaryMuscles: [],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Calf Raises com Halteres', pattern: LO,
    primaryMuscles: ['gastrocnemios'], secondaryMuscles: ['soleo'],
    equipment: [Equipment.HALTERES], level: I },
  { name: 'Seated Calf Raises', pattern: LO,
    primaryMuscles: ['soleo'], secondaryMuscles: ['gastrocnemios'],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'Donkey Calf Raises', pattern: LO,
    primaryMuscles: ['gastrocnemios'], secondaryMuscles: ['soleo'],
    equipment: [Equipment.MAQUINAS], level: I },

  // ══════════════════════════════════════════════════════════════
  // DOMINANTE ANCA — Isquiotibiais / Glúteos / Eretores
  // ══════════════════════════════════════════════════════════════

  // Peso corporal
  { name: 'Glute Bridge', pattern: DA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Glute Bridge Unilateral', pattern: DA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Frog Pump', pattern: DA,
    primaryMuscles: ['gluteos_medios', 'gluteos'], secondaryMuscles: ['adutores'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Donkey Kick', pattern: DA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Fire Hydrant', pattern: DA,
    primaryMuscles: ['gluteos_medios', 'abdutores'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Nordic Curl', pattern: DA,
    primaryMuscles: ['isquiotibiais'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: A },
  { name: 'Good Morning (Sem Peso)', pattern: DA,
    primaryMuscles: ['isquiotibiais', 'eretores_espinhais'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Clamshell com Elástico', pattern: DA,
    primaryMuscles: ['gluteos_medios', 'abdutores'], secondaryMuscles: [],
    equipment: [Equipment.RESISTANCE_BAND], level: I },
  { name: 'Hip Hinge com Elástico', pattern: DA,
    primaryMuscles: ['isquiotibiais', 'gluteos'], secondaryMuscles: ['eretores_espinhais'],
    equipment: [Equipment.RESISTANCE_BAND], level: I, clinicalNotes: ['evitar_lombar'] },

  // Halteres
  { name: 'Romanian Deadlift com Halteres (RDL)', pattern: DA,
    primaryMuscles: ['isquiotibiais', 'gluteos'], secondaryMuscles: ['eretores_espinhais'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Single Leg RDL com Halter', pattern: DA,
    primaryMuscles: ['isquiotibiais', 'gluteos'], secondaryMuscles: ['core', 'eretores_espinhais'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Hip Thrust com Halter', pattern: DA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.HALTERES, Equipment.BANCO], level: I },
  { name: 'Good Morning com Halteres', pattern: DA,
    primaryMuscles: ['isquiotibiais', 'eretores_espinhais'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },

  // Barra
  { name: 'Deadlift Convencional (Levantamento Terra)', pattern: DA,
    primaryMuscles: ['eretores_espinhais', 'gluteos', 'isquiotibiais'], secondaryMuscles: ['trapezio', 'quadriceps', 'core'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Sumo Deadlift', pattern: DA,
    primaryMuscles: ['gluteos', 'adutores', 'quadriceps'], secondaryMuscles: ['isquiotibiais', 'eretores_espinhais'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Romanian Deadlift com Barra (RDL)', pattern: DA,
    primaryMuscles: ['isquiotibiais', 'gluteos'], secondaryMuscles: ['eretores_espinhais'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Stiff Leg Deadlift com Barra', pattern: DA,
    primaryMuscles: ['isquiotibiais', 'eretores_espinhais'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Hip Thrust com Barra', pattern: DA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais', 'core'],
    equipment: [Equipment.BARRA, Equipment.BANCO], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Good Morning com Barra', pattern: DA,
    primaryMuscles: ['isquiotibiais', 'eretores_espinhais'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar'] },

  // Kettlebell
  { name: 'Kettlebell Swing', pattern: DA,
    primaryMuscles: ['gluteos', 'isquiotibiais'], secondaryMuscles: ['core', 'deltoides'],
    equipment: [Equipment.KETTLEBELL], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Single Arm Kettlebell Swing', pattern: DA,
    primaryMuscles: ['gluteos', 'isquiotibiais'], secondaryMuscles: ['core'],
    equipment: [Equipment.KETTLEBELL], level: M, clinicalNotes: ['evitar_lombar'] },

  // Cabo e máquinas
  { name: 'Cable Kickback (Glúteos)', pattern: DA,
    primaryMuscles: ['gluteos'], secondaryMuscles: ['isquiotibiais'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Cable Pull-Through', pattern: DA,
    primaryMuscles: ['gluteos', 'isquiotibiais'], secondaryMuscles: ['eretores_espinhais'],
    equipment: [Equipment.CABO], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Leg Curl Deitado (Máquina)', pattern: DA,
    primaryMuscles: ['isquiotibiais'], secondaryMuscles: ['gluteos', 'gastrocnemios'],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'Leg Curl Sentado (Máquina)', pattern: DA,
    primaryMuscles: ['isquiotibiais'], secondaryMuscles: [],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'Hip Abduction Machine', pattern: DA,
    primaryMuscles: ['gluteos_medios', 'abdutores'], secondaryMuscles: [],
    equipment: [Equipment.MAQUINAS], level: I },
  { name: 'Hip Adduction Machine', pattern: DA,
    primaryMuscles: ['adutores'], secondaryMuscles: [],
    equipment: [Equipment.MAQUINAS], level: I },

  // ══════════════════════════════════════════════════════════════
  // CORE
  // ══════════════════════════════════════════════════════════════

  { name: 'Prancha (Plank)', pattern: CO,
    primaryMuscles: ['core', 'transverso_abdominal'], secondaryMuscles: ['deltoides', 'gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Side Plank', pattern: CO,
    primaryMuscles: ['obliquos', 'quadrado_lombar'], secondaryMuscles: ['gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Plank com Elevação de Braço', pattern: CO,
    primaryMuscles: ['core', 'transverso_abdominal'], secondaryMuscles: ['deltoides', 'gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Dead Bug', pattern: CO,
    primaryMuscles: ['transverso_abdominal', 'core'], secondaryMuscles: ['eretores_espinhais'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Bird Dog', pattern: CO,
    primaryMuscles: ['eretores_espinhais', 'gluteos'], secondaryMuscles: ['core'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Hollow Body Hold', pattern: CO,
    primaryMuscles: ['transverso_abdominal', 'reto_abdominal'], secondaryMuscles: ['iliopsoas'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Crunch', pattern: CO,
    primaryMuscles: ['reto_abdominal'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Sit-up', pattern: CO,
    primaryMuscles: ['reto_abdominal', 'iliopsoas'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Bicycle Crunch', pattern: CO,
    primaryMuscles: ['obliquos', 'reto_abdominal'], secondaryMuscles: [],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Russian Twist com Halter', pattern: CO,
    primaryMuscles: ['obliquos'], secondaryMuscles: ['reto_abdominal'],
    equipment: [Equipment.HALTERES], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Leg Raises (Elevação de Pernas Deitado)', pattern: CO,
    primaryMuscles: ['iliopsoas', 'reto_abdominal'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.PESO_CORPORAL], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Hanging Knee Raises', pattern: CO,
    primaryMuscles: ['iliopsoas', 'reto_abdominal'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.BARRA_FIXA], level: M },
  { name: 'Toes to Bar', pattern: CO,
    primaryMuscles: ['reto_abdominal', 'iliopsoas'], secondaryMuscles: ['obliquos', 'dorsal'],
    equipment: [Equipment.BARRA_FIXA], level: A },
  { name: 'V-Up', pattern: CO,
    primaryMuscles: ['reto_abdominal', 'iliopsoas'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Ab Wheel Rollout', pattern: CO,
    primaryMuscles: ['core', 'transverso_abdominal'], secondaryMuscles: ['dorsal'],
    equipment: [Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_lombar'] },
  { name: 'L-Sit (Paralelas / Chão)', pattern: CO,
    primaryMuscles: ['iliopsoas', 'reto_abdominal'], secondaryMuscles: ['triceps', 'dorsal'],
    equipment: [Equipment.PARALELAS], level: A },
  { name: 'Cable Crunch', pattern: CO,
    primaryMuscles: ['reto_abdominal'], secondaryMuscles: ['obliquos'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Pallof Press (Anti-Rotação)', pattern: CO,
    primaryMuscles: ['transverso_abdominal', 'obliquos'], secondaryMuscles: ['core'],
    equipment: [Equipment.CABO], level: I },
  { name: 'Pallof Press com Elástico', pattern: CO,
    primaryMuscles: ['transverso_abdominal', 'obliquos'], secondaryMuscles: ['core'],
    equipment: [Equipment.RESISTANCE_BAND], level: I },
  { name: 'Windmill com Halter', pattern: CO,
    primaryMuscles: ['obliquos', 'core'], secondaryMuscles: ['deltoides', 'gluteos_medios'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Turkish Get-Up (TGU)', pattern: CO,
    primaryMuscles: ['core', 'deltoides', 'gluteos'], secondaryMuscles: ['quadriceps', 'isquiotibiais'],
    equipment: [Equipment.KETTLEBELL], level: A, clinicalNotes: ['evitar_ombro', 'evitar_lombar'] },
  { name: 'Dragon Flag', pattern: CO,
    primaryMuscles: ['reto_abdominal', 'core'], secondaryMuscles: ['eretores_espinhais'],
    equipment: [Equipment.BANCO, Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_lombar'] },
  { name: 'Landmine Rotation', pattern: CO,
    primaryMuscles: ['obliquos', 'core'], secondaryMuscles: ['deltoides'],
    equipment: [Equipment.BARRA], level: M },
  { name: 'Stir the Pot (Bola de Pilates)', pattern: CO,
    primaryMuscles: ['transverso_abdominal', 'core'], secondaryMuscles: ['deltoides'],
    equipment: [Equipment.PESO_CORPORAL], level: M },

  // ══════════════════════════════════════════════════════════════
  // LOCOMOÇÃO — Cardio / Full Body / Flexibilidade
  // ══════════════════════════════════════════════════════════════

  // Full Body / Cardio funcional
  { name: 'Burpees', pattern: LO,
    primaryMuscles: ['quadriceps', 'peitoral', 'deltoides'], secondaryMuscles: ['core', 'gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Burpees com Pull-up', pattern: LO,
    primaryMuscles: ['dorsal', 'quadriceps', 'peitoral'], secondaryMuscles: ['core', 'biceps'],
    equipment: [Equipment.BARRA_FIXA, Equipment.PESO_CORPORAL], level: A },
  { name: 'Thrusters com Halteres', pattern: LO,
    primaryMuscles: ['quadriceps', 'deltoides', 'gluteos'], secondaryMuscles: ['core', 'triceps'],
    equipment: [Equipment.HALTERES], level: M },
  { name: 'Thrusters com Barra', pattern: LO,
    primaryMuscles: ['quadriceps', 'deltoides', 'gluteos'], secondaryMuscles: ['core', 'triceps'],
    equipment: [Equipment.BARRA], level: M, clinicalNotes: ['evitar_lombar', 'evitar_ombro'] },
  { name: 'Clean & Press com Halteres', pattern: LO,
    primaryMuscles: ['gluteos', 'deltoides', 'trapezio'], secondaryMuscles: ['core', 'biceps'],
    equipment: [Equipment.HALTERES], level: M, clinicalNotes: ['evitar_lombar'] },
  { name: 'Kettlebell Clean & Press', pattern: LO,
    primaryMuscles: ['gluteos', 'deltoides'], secondaryMuscles: ['core', 'triceps'],
    equipment: [Equipment.KETTLEBELL], level: M, clinicalNotes: ['evitar_lombar', 'evitar_ombro'] },
  { name: 'Mountain Climbers', pattern: LO,
    primaryMuscles: ['core', 'iliopsoas'], secondaryMuscles: ['deltoides', 'quadriceps'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Bear Crawl', pattern: LO,
    primaryMuscles: ['core', 'deltoides'], secondaryMuscles: ['quadriceps', 'gluteos'],
    equipment: [Equipment.PESO_CORPORAL], level: M },
  { name: 'Inchworm', pattern: LO,
    primaryMuscles: ['deltoides', 'isquiotibiais'], secondaryMuscles: ['core'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Box Jump', pattern: LO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['gastrocnemios', 'core'],
    equipment: [Equipment.PESO_CORPORAL], level: M, clinicalNotes: ['evitar_joelho'] },
  { name: 'Jumping Jacks', pattern: LO,
    primaryMuscles: ['deltoides_lateral', 'adutores'], secondaryMuscles: ['gastrocnemios'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'High Knees', pattern: LO,
    primaryMuscles: ['iliopsoas', 'quadriceps'], secondaryMuscles: ['core', 'gastrocnemios'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Butt Kicks', pattern: LO,
    primaryMuscles: ['isquiotibiais'], secondaryMuscles: ['gastrocnemios'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Lateral Shuffle', pattern: LO,
    primaryMuscles: ['adutores', 'abdutores', 'quadriceps'], secondaryMuscles: ['gastrocnemios'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Salto à Corda', pattern: LO,
    primaryMuscles: ['gastrocnemios', 'quadriceps'], secondaryMuscles: ['core'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_tornozelo'] },
  { name: 'Double Under (Salto à Corda Duplo)', pattern: LO,
    primaryMuscles: ['gastrocnemios', 'quadriceps'], secondaryMuscles: ['core', 'deltoides'],
    equipment: [Equipment.PESO_CORPORAL], level: A, clinicalNotes: ['evitar_tornozelo'] },

  // Cardio com equipamento
  { name: 'Corrida / Passadeira', pattern: LO,
    primaryMuscles: ['quadriceps', 'isquiotibiais', 'gluteos', 'gastrocnemios'], secondaryMuscles: ['core'],
    equipment: [Equipment.CARDIO_EQ], level: I, clinicalNotes: ['evitar_joelho', 'evitar_tornozelo'] },
  { name: 'Caminhada Inclinada', pattern: LO,
    primaryMuscles: ['gluteos', 'isquiotibiais', 'gastrocnemios'], secondaryMuscles: ['core'],
    equipment: [Equipment.CARDIO_EQ], level: I },
  { name: 'Bicicleta Estática', pattern: LO,
    primaryMuscles: ['quadriceps', 'gluteos'], secondaryMuscles: ['gastrocnemios'],
    equipment: [Equipment.CARDIO_EQ], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Elíptica', pattern: LO,
    primaryMuscles: ['quadriceps', 'gluteos', 'isquiotibiais'], secondaryMuscles: ['gastrocnemios', 'core'],
    equipment: [Equipment.CARDIO_EQ], level: I },
  { name: 'Remo (Máquina)', pattern: LO,
    primaryMuscles: ['dorsal', 'isquiotibiais', 'gluteos'], secondaryMuscles: ['biceps', 'core'],
    equipment: [Equipment.CARDIO_EQ], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Ski Erg', pattern: LO,
    primaryMuscles: ['dorsal', 'core', 'deltoides'], secondaryMuscles: ['triceps', 'gluteos'],
    equipment: [Equipment.CARDIO_EQ], level: I },
  { name: 'Assault Bike', pattern: LO,
    primaryMuscles: ['quadriceps', 'gluteos', 'deltoides'], secondaryMuscles: ['core', 'isquiotibiais'],
    equipment: [Equipment.CARDIO_EQ], level: I },

  // Flexibilidade / Mobilidade
  { name: 'Hip Flexor Stretch (Ajoelhado)', pattern: LO,
    primaryMuscles: ['iliopsoas'], secondaryMuscles: ['quadriceps'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: 'Pigeon Pose (Abertura de Anca)', pattern: LO,
    primaryMuscles: ['gluteos', 'iliopsoas'], secondaryMuscles: ['adutores'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_joelho'] },
  { name: "World's Greatest Stretch", pattern: LO,
    primaryMuscles: ['iliopsoas', 'isquiotibiais', 'deltoides'], secondaryMuscles: ['gluteos', 'obliquos'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Cat-Cow (Mobilidade Torácica)', pattern: LO,
    primaryMuscles: ['eretores_espinhais'], secondaryMuscles: ['core'],
    equipment: [Equipment.PESO_CORPORAL], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Toalha / Foam Roller — Dorsal', pattern: LO,
    primaryMuscles: ['eretores_espinhais'], secondaryMuscles: ['romboides'],
    equipment: [Equipment.FOAM_ROLLER], level: I, clinicalNotes: ['evitar_lombar'] },
  { name: 'Foam Roller — ITB / Quads', pattern: LO,
    primaryMuscles: ['quadriceps'], secondaryMuscles: [],
    equipment: [Equipment.FOAM_ROLLER], level: I },
  { name: 'Hip 90/90 Stretch', pattern: LO,
    primaryMuscles: ['gluteos_medios', 'iliopsoas'], secondaryMuscles: ['adutores'],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Couch Stretch (Quadríceps)', pattern: LO,
    primaryMuscles: ['quadriceps', 'iliopsoas'], secondaryMuscles: [],
    equipment: [Equipment.PESO_CORPORAL], level: I },
  { name: 'Chest Opener (Abertura de Peito)', pattern: LO,
    primaryMuscles: ['peitoral'], secondaryMuscles: ['deltoides_anterior'],
    equipment: [Equipment.RESISTANCE_BAND], level: I, clinicalNotes: ['evitar_ombro'] },
];
